name: LogTrade
version: '${version}'
main: me.xpyex.plugin.bukkit.logtrade.LogTrade
softdepend: [ ProtocolLib ]
authors: [ XPYEX ]
description: TradeMe
commands:
  logtrade:
    description: "LogTrade"